-- MySQL Script generated by MySQL Workbench
-- Tue Jul 23 16:03:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gdemandes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gdemandes` ;

-- -----------------------------------------------------
-- Schema gdemandes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gdemandes` DEFAULT CHARACTER SET latin1 ;
USE `gdemandes` ;

-- -----------------------------------------------------
-- Table `gdemandes`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdemandes`.`users` ;

CREATE TABLE IF NOT EXISTS `gdemandes`.`users` (
  `user_id` VARCHAR(20) NOT NULL,
  `user_nom` VARCHAR(30) NULL DEFAULT NULL,
  `user_prenom` VARCHAR(30) NULL DEFAULT NULL,
  `user_email` VARCHAR(50) NULL DEFAULT NULL,
  `user_fonction` VARCHAR(20) NULL DEFAULT NULL,
  `user_superieur_id` VARCHAR(20) NULL DEFAULT NULL,
  `user_password` VARCHAR(100) NULL DEFAULT NULL,
  `user_type` ENUM('utilisateur', 'validateur', 'magasinier', 'administrateur') NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gdemandes`.`demandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdemandes`.`demandes` ;

CREATE TABLE IF NOT EXISTS `gdemandes`.`demandes` (
  `demande_id` INT(11) NOT NULL AUTO_INCREMENT,
  `demandeur_id` VARCHAR(30) NOT NULL,
  `demande_statut` ENUM('attente de validation', 'validée', 'refuser', 'chez le magasinier', 'cloturée') NULL DEFAULT NULL,
  `validateur_id` VARCHAR(30) NOT NULL,
  `demande_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`demande_id`),
  INDEX `demandeur_id_idx` (`demandeur_id` ASC) VISIBLE,
  INDEX `validateur_id_idx` (`validateur_id` ASC) VISIBLE,
  CONSTRAINT `demandeur_id`
    FOREIGN KEY (`demandeur_id`)
    REFERENCES `gdemandes`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `validateur_id`
    FOREIGN KEY (`validateur_id`)
    REFERENCES `gdemandes`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gdemandes`.`fournisseur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdemandes`.`fournisseur` ;

CREATE TABLE IF NOT EXISTS `gdemandes`.`fournisseur` (
  `fournisseur_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fournisseur_nom` VARCHAR(30) NULL DEFAULT NULL,
  `fournisseur_phone` VARCHAR(45) NULL DEFAULT NULL,
  `fournisseur_email` VARCHAR(30) NULL DEFAULT NULL,
  `fournisseur_website` VARCHAR(200) NULL DEFAULT NULL,
  `fournisseur_address` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`fournisseur_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gdemandes`.`produits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdemandes`.`produits` ;

CREATE TABLE IF NOT EXISTS `gdemandes`.`produits` (
  `produit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `produit_categorie` VARCHAR(30) NULL DEFAULT NULL,
  `produit_serial` VARCHAR(200) NULL DEFAULT NULL,
  `produit_picture` VARCHAR(200) NULL DEFAULT NULL,
  `produit_designation` VARCHAR(255) NULL DEFAULT NULL,
  `produit_stock_qte` INT(11) NULL DEFAULT NULL,
  `fournisseur_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`produit_id`),
  INDEX `id_fournisseur_idx` (`fournisseur_id` ASC) VISIBLE,
  CONSTRAINT `id_fournisseur`
    FOREIGN KEY (`fournisseur_id`)
    REFERENCES `gdemandes`.`fournisseur` (`fournisseur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gdemandes`.`produits_demandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gdemandes`.`produits_demandes` ;

CREATE TABLE IF NOT EXISTS `gdemandes`.`produits_demandes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `demande_id` INT(11) NULL DEFAULT NULL,
  `produit_id` INT(11) NULL DEFAULT NULL,
  `qte_demander` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_demande_idx` (`demande_id` ASC) VISIBLE,
  INDEX `id_produit_idx` (`produit_id` ASC) VISIBLE,
  CONSTRAINT `id_demande`
    FOREIGN KEY (`demande_id`)
    REFERENCES `gdemandes`.`demandes` (`demande_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_produit`
    FOREIGN KEY (`produit_id`)
    REFERENCES `gdemandes`.`produits` (`produit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
